columns:
  channel_name:
    caseSensitive: false
    dataType: 1
    generated: false
    name: CHANNEL_NAME
    nullable: false
    primaryKey: true
    unsigned: false
    visible: true
  desired_delay:
    caseSensitive: false
    dataType: 4
    generated: false
    name: DESIRED_DELAY
    nullable: false
    primaryKey: false
    unsigned: false
    visible: true
  privilege_checks_user:
    caseSensitive: true
    dataType: -1
    generated: false
    name: PRIVILEGE_CHECKS_USER
    nullable: true
    primaryKey: false
    unsigned: false
    visible: true
  require_row_format:
    caseSensitive: false
    dataType: 1
    generated: false
    name: REQUIRE_ROW_FORMAT
    nullable: false
    primaryKey: false
    unsigned: false
    visible: true
  require_table_primary_key_check:
    caseSensitive: false
    dataType: 1
    generated: false
    name: REQUIRE_TABLE_PRIMARY_KEY_CHECK
    nullable: false
    primaryKey: false
    unsigned: false
    visible: true
  assign_gtids_to_anonymous_transactions_type:
    caseSensitive: false
    dataType: 1
    generated: false
    name: ASSIGN_GTIDS_TO_ANONYMOUS_TRANSACTIONS_TYPE
    nullable: false
    primaryKey: false
    unsigned: false
    visible: true
  assign_gtids_to_anonymous_transactions_value:
    caseSensitive: true
    dataType: -1
    generated: false
    name: ASSIGN_GTIDS_TO_ANONYMOUS_TRANSACTIONS_VALUE
    nullable: true
    primaryKey: false
    unsigned: false
    visible: true
indexes:
  primary:
    columns:
    - CHANNEL_NAME
    name: PRIMARY
    unique: true
name: replication_applier_configuration
type: TABLE
