columns:
  name:
    caseSensitive: false
    dataType: 1
    generated: false
    name: name
    nullable: false
    primaryKey: true
    unsigned: false
    visible: true
  version:
    caseSensitive: false
    dataType: -5
    generated: false
    name: version
    nullable: false
    primaryKey: false
    unsigned: true
    visible: true
indexes:
  primary:
    columns:
    - name
    name: PRIMARY
    unique: true
name: replication_group_configuration_version
type: TABLE
